"""
Feishu Webhook Sender Module - Enhanced based on TrendRadar
支持飞书卡片 Markdown 格式优化
"""
import re
import logging
from typing import Dict, Optional
from src.config import FEISHU_WEBHOOK_URL

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# 飞书支持的 Markdown 特性
FEISHU_MARKDOWN_GUIDE = {
    "supported": [
        "**粗体**",
        "[链接文本](URL)",
        "<font color='red/green/grey/orange/blue'>彩色文本</font>",
        "---（分割线）",
        "换行分隔段落",
    ],
    "unsupported": [
        "# 标题语法（不渲染为标题样式）",
        "> 引用块",
        "表格 / 图片嵌入",
    ],
    "prompt": (
        "飞书卡片 Markdown 格式化策略：\n"
        "1. 用 **粗体** 作小标题和重点词\n"
        "2. 用 <font color='red'>红色</font> 标记紧急/重要内容\n"
        "3. 用 <font color='grey'>灰色</font> 标记辅助信息（时间、来源）\n"
        "4. 用 <font color='orange'>橙色</font> 标记警告\n"
        "5. 用 <font color='green'>绿色</font> 标记正面/成功信息\n"
        "6. 用 [文本](URL) 添加可点击链接\n"
        "7. 用 --- 分割不同主题区域\n"
        "8. 不要用 # 标题语法（卡片内不渲染）\n"
        "9. 不要用 > 引用语法\n"
        "10. 用换行 + 粗体模拟层级结构"
    ),
}


def adapt_markdown_for_feishu(text: str) -> str:
    """将通用 Markdown 适配为飞书卡片 Markdown 格式

    飞书卡片支持：**粗体**, [链接](url), <font color='...'>, ---
    不支持：# 标题, > 引用块
    """
    # 将 # 标题转换为粗体（飞书卡片不渲染标题语法）
    text = re.sub(r'^#{1,6}\s+(.+)$', r'**\1**', text, flags=re.MULTILINE)
    # 去除引用语法前缀（飞书不支持）
    text = re.sub(r'^>\s*', '', text, flags=re.MULTILINE)
    # 清理多余空行（保留最多两个）
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def send_to_feishu(message: str, webhook_url: str = None, msg_type: str = "text") -> bool:
    """
    Send message to Feishu via webhook (sync version)

    Args:
        message: Message content to send
        webhook_url: Feishu webhook URL (uses config default if None)
        msg_type: Message type (text, post, interactive, card)

    Returns:
        bool: True if successful, False otherwise
    """
    if webhook_url is None:
        webhook_url = FEISHU_WEBHOOK_URL

    # 适配飞书格式
    adapted_message = adapt_markdown_for_feishu(message)

    payload = {
        "msg_type": msg_type,
        "content": {
            "text": adapted_message
        },
    }

    try:
        import requests
        resp = requests.post(webhook_url, json=payload, timeout=30)
        data = resp.json()
        ok = resp.status_code == 200 and (data.get("code") == 0 or data.get("StatusCode") == 0)

        if ok:
            logger.info(f"Message sent to Feishu successfully")
            return True
        else:
            detail = data.get("msg") or data.get("StatusMessage", "")
            logger.error(f"Failed to send to Feishu: HTTP {resp.status_code}, {detail}")
            return False
    except Exception as e:
        logger.error(f"Error sending to Feishu: {e}")
        return False


async def send_notification_to_feishu(message: str) -> bool:
    """
    Send a notification message to Feishu (async wrapper)

    Args:
        message: Notification message to send

    Returns:
        bool: True if successful, False otherwise
    """
    return send_to_feishu(message)


def format_report_for_feishu(report_content: str, chart_summary: str, report_date: str) -> str:
    """
    Format report for Feishu text message with enhanced formatting

    Args:
        report_content: Markdown report content
        chart_summary: Chart data summary
        report_date: Report date

    Returns:
        Formatted message string
    """
    # 适配报告内容为飞书格式
    adapted_report = adapt_markdown_for_feishu(report_content)
    adapted_summary = adapt_markdown_for_feishu(chart_summary)

    # 使用飞书颜色标签增强可读性
    message = f"""**《全球地缘政治与安全战略日报》**

<font color='grey'>📅 {report_date}</font>

{adapted_report}

{adapted_summary}

---
<font color='grey'>Generated by Geopolitical Intelligence Analysis System</font>
"""
    return message


def format_error_message(error: str) -> str:
    """
    Format error message for Feishu with color highlighting

    Args:
        error: Error description

    Returns:
        Formatted error message
    """
    return f"""<font color='red'>**地缘政治情报日报生成失败**</font>

错误信息: {error}

<font color='grey'>请检查系统日志获取详细信息。</font>
"""


def format_success_summary(total_articles: int, high_value_articles: int) -> str:
    """
    Format success summary for Feishu with color highlighting

    Args:
        total_articles: Total number of articles processed
        high_value_articles: Number of high-value articles (score >= 7)

    Returns:
        Formatted summary string
    """
    return f"""
<font color='green'>**✅ 日报生成成功**</font>

📊 **统计数据:**
• 今日处理文章总数: **{total_articles}**
• 高价值情报条数 (≥7分): **{high_value_articles}**
"""


def send_report_to_feishu(
    report_content: str,
    chart_data: Dict,
    report_date: str,
    total_articles: int,
    high_value_articles: int,
    webhook_url: str = None,
) -> bool:
    """
    Send report to Feishu via webhook (sync wrapper for use in async context)

    Args:
        report_content: Markdown report content
        chart_data: Chart data dictionary
        report_date: Report date
        total_articles: Total articles processed
        high_value_articles: High-value articles count
        webhook_url: Feishu webhook URL

    Returns:
        bool: True if successful
    """
    # Import chart summary function
    from src.charts.generator import generate_chart_summary
    chart_summary = generate_chart_summary(chart_data)

    # Build message
    message = format_report_for_feishu(report_content, chart_summary, report_date)

    # Append success summary
    summary = format_success_summary(total_articles, high_value_articles)
    full_message = message + summary

    # Use sync send_to_feishu function
    return send_to_feishu(full_message, webhook_url=webhook_url)


async def send_to_feishu_async(message: str, webhook_url: str = None, msg_type: str = "text") -> bool:
    """
    Async version of send_to_feishu

    Args:
        message: Message content to send
        webhook_url: Feishu webhook URL
        msg_type: Message type

    Returns:
        bool: True if successful
    """
    if webhook_url is None:
        webhook_url = FEISHU_WEBHOOK_URL

    # 适配飞书格式
    adapted_message = adapt_markdown_for_feishu(message)

    payload = {
        "msg_type": msg_type,
        "content": {
            "text": adapted_message
        },
    }

    try:
        import aiohttp
        async with aiohttp.ClientSession() as session:
            async with session.post(webhook_url, json=payload, timeout=aiohttp.ClientTimeout(total=30)) as response:
                if response.status == 200:
                    result = await response.json()
                    ok = result.get("code") == 0 or result.get("StatusCode") == 0
                    if ok:
                        logger.info(f"Message sent to Feishu successfully")
                        return True
                    else:
                        detail = result.get("msg") or result.get("StatusMessage", "")
                        logger.error(f"Failed to send to Feishu: {detail}")
                        return False
                else:
                    error_text = await response.text()
                    logger.error(f"Failed to send to Feishu: HTTP {response.status}, {error_text}")
                    return False
    except Exception as e:
        logger.error(f"Error sending to Feishu: {e}")
        return False


def get_feishu_format_guide() -> Dict:
    """
    Get Feishu format guide

    Returns:
        Format guide dictionary
    """
    return FEISHU_MARKDOWN_GUIDE
